apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yabbspvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yabbscicd 
spec:
  selector:
    matchLabels:
      app: yabbscicd
  replicas: 1
  template:
    metadata:
      labels:
        app: yabbscicd 
    spec:
      containers:
      - name: yabbscicd 
        image: index.docker.io/idjohson/yabbs
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: yabbspvc
